# Generated by Django 3.1 on 2022-02-12 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20220205_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descrition',
            new_name='description',
        ),
    ]
